"""empty message

Revision ID: 514defeb7a37
Revises: 8989371de8b9
Create Date: 2024-07-10 23:24:53.835692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '514defeb7a37'
down_revision = '8989371de8b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pitches', schema=None) as batch_op:
        batch_op.alter_column('image_data',
               existing_type=sa.BLOB(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pitches', schema=None) as batch_op:
        batch_op.alter_column('image_data',
               existing_type=sa.String(),
               type_=sa.BLOB(),
               existing_nullable=False)

    # ### end Alembic commands ###
